### ISSUE TITLE
Рефакт

### ISSUE THREAD

**Issue by DitriXNew** [VSydorenko/SMP_OnlineExchange#1]
- [x] Надо сделать папку с проектом, и туда разместить файлы EDT, чтобы они не болтались в общем гите.

Однако, перемещать надо в папку при помощи команд:
$ mkdir include
$ git mv common include
$ git rm -r common
$ git add include/common

Чтобы сохранилась история.

- [x] Также можно удалить файлы:

index.md
.gitignore

- [x] Кроме этого в рид ми стоит указать версию EDT на которой ведется разработка, версию платформы и, в случае расширения - можно прям тестовую базу скинуть, на которой будет идти разработка.

**Comment by VSydorenko** [comment]
Я з тими папками проекта якраз і промудохався найбільше. Подивився інші рішення і подумав (може, зря), що в корені якраз буде саме правильніше.

Github Desktop прекрасно справився із переміщеннями файлів по папках сам. Це щось нове, бо раніше він не відслідковував переміщення.

Дякую за рекомендації, поправлю
